# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.define "web" do |web|
        web.vm.box = "centos/7"
        web.vm.network "forwarded_port", guest: 80, host: 1234, host_ip: "127.0.0.1"
        web.vm.define "webserver"
    end

    config.vm.define "db" do |db|
        db.vm.box = "centos/7"
        db.vm.define "dbserver"
    end

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "../deploy.yml"
        ansible.groups = {
            "webserver" => ["web"],
            "dbserver" => ["db"],
            "dev_webservers" => ["web"]
        }
    end
end

# Create a private network, which allows host-only access to the machine
# using a specific IP.
# config.vm.network "private_network", ip: "192.168.33.10"
