# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.network "forwarded_port", guest: 80, host: 1234, host_ip: "127.0.0.1"

    # Create a private network, which allows host-only access to the machine
    # using a specific IP.
    # config.vm.network "private_network", ip: "192.168.33.10"
    config.vm.define "webserver"
    config.vm.provision :ansible do |ansible|
      ansible.playbook = "../deploy.yml"
      ansible.groups = {
        "webservers" => ["webserver"]
      }
    end
end
