---
# file: roles/common/tasks/main.yml

- name: install basic packages
  yum:
    name: "{{ basic_packages }}"
    state: present
  notify: restart-ntpd
  tags:
    - ntp
    - git

- name: enable ntp
  service:
    name: ntpd
    state: started
    enabled: yes
  tags: ntp

- name: transfer github keys
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: 'git-config', dest: '/root/.gitconfig' }
    - { src: 'git-credentials.j2', dest: '/root/.git-credentials' }
  tags: git

- name: download webpage files from git
  git:
    repo: "{{ repository }}"
    dest: /usr/share/nginx/html/
    force: yes
  tags: git
