---
# file: webserver.yml

- hosts: all
  roles:
    - common

- hosts: webservers
  roles:
    - webserver
    - nginx

- hosts: dev_webservers
  roles:
    - rsync

- hosts: test_webservers
  roles:
    - github

- hosts: webservers
  roles:
    - node

- hosts: dbservers
  roles:
    - db

- hosts: dev_dbservers, test_dbservers
  roles:
    - seed

- hosts: dev_webservers
  roles:
    - dev_start

- hosts: test_webservers
  roles:
    - start
