---
# file: roles/webserver/tasks/main.yml

- name: install nginx
  yum:
    name: nginx
    state: present
  tags: nginx

- name: install node
  yum:
    name: nodejs
    state: present
  tags: node

- name: start nginx
  service:
    name: nginx
    state: started
    enabled: yes
  tags: nginx
