---
# file: roles/webserver/tasks/main.yml

- name: Instal nginx
  yum:
    name: nginx
    state: present
  tags:
    - nginx

- name: Ensure nginx is running
  service:
    name: nginx
    state: started
    enabled: yes
  tags:
    - nginx
