---
# file: roles/rsync/tasks/mail.yml

- name: copy local working directory to dev box
  synchronize:
    src: "{{ dev_directory }}"
    dest: "/usr/share/nginx/html/"
    delete: yes
    recursive: yes
